name: Setup AutoTest Database

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-database:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install curl
        run: choco install curl -y
        shell: powershell

      - name: Insert Data via API
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          curl -X POST "$env:API_URL/api/database/insert" -H "Content-Type: application/json" -d "{\"Name\":\"John\",\"Surname\":\"Doe\",\"Email\":\"john.doe@example.com\"}"
          curl -X POST "$env:API_URL/api/database/insert" -H "Content-Type: application/json" -d "{\"Name\":\"Jane\",\"Surname\":\"Smith\",\"Email\":\"jane.smith@example.com\"}"
