name: Setup AutoTest Database

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SQL Server Tools (sqlcmd)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc -o microsoft.asc
          sudo gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg microsoft.asc
          rm microsoft.asc
          curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools
          echo "/opt/mssql-tools/bin" >> $GITHUB_PATH

      - name: Run SQL Setup Script
        env:
          SQL_SERVER: rnvxn-41-116-4-193.a.free.pinggy.link,33357
          SQL_USER: Auto_user
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          echo "Starting SQL setup at $(date)"
          sqlcmd -S ${SQL_SERVER} -U ${SQL_USER} -P ${SQL_PASSWORD} -b -t 30 -i scripts/setup-database.sql || echo "Failed to execute SQL script"
          echo "Finished at $(date)"
