name: Setup SQL Server Database

on:
  push:
    branches: [ master ]  # Adjust to master if needed
  workflow_dispatch:

jobs:
  setup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl libunwind8 libsss-nss-idmap0

      - name: Download and install mssql-tools
        run: |
          curl -O https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/m/mssql-tools18/mssql-tools18_18.2.1.1-1_amd64.deb
          sudo dpkg -i mssql-tools18_18.2.1.1-1_amd64.deb
          sudo apt-get install -f -y  # Fix any missing dependencies
          rm mssql-tools18_18.2.1.1-1_amd64.deb

      - name: Setup Database, User, Table, Procedure, and Data
        env:
          SQL_SERVER: rnvxn-41-116-4-193.a.free.pinggy.link,33357  # Replace with new endpoint if offline
        run: |
          echo "Starting SQL setup at $(date)"
          /opt/mssql-tools18/bin/sqlcmd -S ${SQL_SERVER} -U Auto_user -P ${{ secrets.SQL_PASSWORD }} -b -t 30 -i scripts/setup-database.sql || echo "Failed to execute SQL script"
          echo "Finished at $(date)"
