name: Setup SQL Server Database

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify SQL file exists
        run: |
          ls -la
          cd scripts
          if [ -f "setup-database.sql" ]; then
            echo "SQL file found in scripts"
            cat setup-database.sql
          else
            echo "SQL file NOT found in scripts"
            exit 1
          fi

      - name: Run SQL Setup Script with Docker
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          echo "Starting SQL setup at $(date)"
          docker run --rm -v $(pwd):/work mcr.microsoft.com/mssql/server:2019-latest \
            bash -c "echo 'Running sqlcmd' && /opt/mssql-tools18/bin/sqlcmd -S ${SQL_SERVER} -U ${SQL_USER} -P '${SQL_PASSWORD}' -C -b -t 30 -i /work/scripts/setup-database.sql || echo 'sqlcmd failed'"
          echo "Finished at $(date)"

  deploy:
    runs-on: ubuntu-latest
    needs: development
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify SQL file exists
        run: |
          ls -la
          cd scripts
          if [ -f "deploy-database.sql" ]; then
            echo "SQL file found in root"
            cat deploy-database.sql
          else
            echo "SQL file NOT found in root"
            exit 1
          fi

      - name: Deploy SQL Script to Another User’s Device
        env:
          DEPLOY_SQL_SERVER: ${{ secrets.DEPLOY_SQL_SERVER }}
          DEPLOY_SQL_USER: ${{ secrets.DEPLOY_SQL_USER }}
          DEPLOY_SQL_PASSWORD: ${{ secrets.DEPLOY_SQL_PASSWORD }}
        run: |
          echo "Starting deployment at $(date)"
          docker run --rm -v $(pwd):/work mcr.microsoft.com/mssql/server:2019-latest \
            bash -c "echo 'Running sqlcmd for deploy' && /opt/mssql-tools18/bin/sqlcmd -S ${DEPLOY_SQL_SERVER} -U ${DEPLOY_SQL_USER} -P '${DEPLOY_SQL_PASSWORD}' -C -b -t 30 -i /work/scripts/deploy-database.sql || echo 'Deploy sqlcmd failed'"
          echo "Finished deployment at $(date)"
