name: Setup AutoTest Database

on:
  push:
    branches:
      - master  # Note: You used 'master', ensure this matches your branch
  workflow_dispatch:

jobs:
  setup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SQL Server Tools (sqlcmd)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
          curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools
          echo "/opt/mssql-tools/bin" >> $GITHUB_PATH
          sqlcmd -?  # Verify sqlcmd installed

      - name: Setup Database and Insert Data
        env:
          SQL_SERVER: rntod-197-184-78-105.a.free.pinggy.link:35573
          SQL_USER: Auto_user
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          echo "Starting database setup at $(date)"
          sqlcmd -S ${SQL_SERVER} -U ${SQL_USER} -P ${SQL_PASSWORD} -b -t 30 -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'AutoTest') CREATE DATABASE AutoTest;" || echo "Failed to create database"
          sqlcmd -S ${SQL_SERVER} -U ${SQL_USER} -P ${SQL_PASSWORD} -b -t 30 -d AutoTest -Q "IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'user') CREATE TABLE [dbo].[user] (ID INT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(100), Surname NVARCHAR(100), Email NVARCHAR(100));" || echo "Failed to create table"
          sqlcmd -S ${SQL_SERVER} -U ${SQL_USER} -P ${SQL_PASSWORD} -b -t 30 -d AutoTest -Q "IF EXISTS (SELECT * FROM sys.procedures WHERE name = 'InsertUser') DROP PROCEDURE InsertUser; CREATE PROCEDURE InsertUser @Name NVARCHAR(100), @Surname NVARCHAR(100), @Email NVARCHAR(100) AS BEGIN INSERT INTO [dbo].[user] (Name, Surname, Email) VALUES (@Name, @Surname, @Email); END;" || echo "Failed to create procedure"
          sqlcmd -S ${SQL_SERVER} -U ${SQL_USER} -P ${SQL_PASSWORD} -b -t 30 -d AutoTest -Q "EXEC InsertUser 'John', 'Doe', 'john.doe@example.com';" || echo "Failed to insert John"
          sqlcmd -S ${SQL_SERVER} -U ${SQL_USER} -P ${SQL_PASSWORD} -b -t 30 -d AutoTest -Q "EXEC InsertUser 'Jane', 'Smith', 'jane.smith@example.com';" || echo "Failed to insert Jane"
          echo "Finished at $(date)"
