name: Setup AutoTest Database

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-database:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install curl
        run: choco install curl -y
        shell: powershell

      - name: Insert Data via API
        run: |
          curl -X POST "https://pj-julian-injuries-writers.trycloudflare.com/api/database/insert" -H "Content-Type: application/json" -d '{"Name":"John","Surname":"Doe","Email":"john.doe@example.com"}'
          curl -X POST "https://pj-julian-injuries-writers.trycloudflare.com/api/database/insert" -H "Content-Type: application/json" -d '{"Name":"Jane","Surname":"Smith","Email":"jane.smith@example.com"}'
