name: SQL Debugging Workflow

on:
  push:
    branches:
      - master

jobs:
  debug-sql-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in the Database folder
      run: ls -la $(pwd)/Database

    - name: Verify SQL file path inside the container
      run: |
        docker run --rm -v $(pwd)/Database:/scripts ubuntu:latest ls -la /scripts
