name: SQL Automation

on:
  push:
    branches:
      - master

jobs:
  automate-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in the Database folder
      run: ls -la $(pwd)/Database

    - name: Install SQL Server Client Tools
      run: |
        # Install mssql-tools using Docker
        docker run --rm mcr.microsoft.com/mssql-tools /opt/mssql-tools/bin/sqlcmd -?

    - name: Set up SSH Tunnel
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        AWS_EC2_IP: ${{ secrets.AWS_EC2_IP }}
      run: |
        echo "$SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem

        # Create the .ssh directory if it doesn't exist
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        # Fetch the host key and add it to known_hosts
        ssh-keyscan $AWS_EC2_IP >> ~/.ssh/known_hosts

        # Set up the SSH tunnel
        ssh -i key.pem -L 1433:localhost:1433 ubuntu@$AWS_EC2_IP -N -f

    - name: Run SQL Scripts
      env:
        SQL_SERVER: localhost
        SQL_USER: ${{ secrets.SQL_USER }}
        SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      run: |
        echo "Running SQL scripts..."
        
        # Running SQL scripts directly from the Database folder
        docker run --rm -v $(pwd)/Database:/scripts mcr.microsoft.com/mssql-tools /opt/mssql-tools/bin/sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -i /scripts/create-database-and-user.sql
        docker run --rm -v $(pwd)/Database:/scripts mcr.microsoft.com/mssql-tools /opt/mssql-tools/bin/sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASSWORD -d AutoTest -i /scripts/create-table-and-procedure.sql
